// Gerado por bolsa_familia_hub/build_graph.py — NÃO editar à mão.
// Fonte: pipelines/databricks.yml + parsing estático dos notebooks.
MATCH (n) DETACH DELETE n;

CREATE CONSTRAINT table_full_name IF NOT EXISTS FOR (t:Table) REQUIRE t.full_name IS UNIQUE;
CREATE CONSTRAINT job_name IF NOT EXISTS FOR (j:Job) REQUIRE j.name IS UNIQUE;
CREATE CONSTRAINT task_key IF NOT EXISTS FOR (t:Task) REQUIRE t.key IS UNIQUE;

CREATE (:Table {full_name: 'bronze.bcb_ipca_raw', schema: 'bronze', name: 'bcb_ipca_raw', layer: 'bronze'});
CREATE (:Table {full_name: 'bronze.cnes_equipamentos', schema: 'bronze', name: 'cnes_equipamentos', layer: 'bronze'});
CREATE (:Table {full_name: 'bronze.emendas_pagamentos', schema: 'bronze', name: 'emendas_pagamentos', layer: 'bronze'});
CREATE (:Table {full_name: 'bronze.geobr_municipios_geo', schema: 'bronze', name: 'geobr_municipios_geo', layer: 'bronze'});
CREATE (:Table {full_name: 'bronze.geobr_municipios_meta', schema: 'bronze', name: 'geobr_municipios_meta', layer: 'bronze'});
CREATE (:Table {full_name: 'bronze.ibge_municipios_populacao_raw', schema: 'bronze', name: 'ibge_municipios_populacao_raw', layer: 'bronze'});
CREATE (:Table {full_name: 'bronze.ibge_populacao_raw', schema: 'bronze', name: 'ibge_populacao_raw', layer: 'bronze'});
CREATE (:Table {full_name: 'bronze.pbf_pagamentos', schema: 'bronze', name: 'pbf_pagamentos', layer: 'bronze'});
CREATE (:Table {full_name: 'bronze.rais_vinculos', schema: 'bronze', name: 'rais_vinculos', layer: 'bronze'});
CREATE (:Table {full_name: 'bronze.sih_aih_rd_uropro', schema: 'bronze', name: 'sih_aih_rd_uropro', layer: 'bronze'});
CREATE (:Table {full_name: 'gold.emendas_estados_df', schema: 'gold', name: 'emendas_estados_df', layer: 'gold'});
CREATE (:Table {full_name: 'gold.equipamentos_estados_ano', schema: 'gold', name: 'equipamentos_estados_ano', layer: 'gold'});
CREATE (:Table {full_name: 'gold.finops_daily_spend', schema: 'gold', name: 'finops_daily_spend', layer: 'gold'});
CREATE (:Table {full_name: 'gold.finops_run_costs', schema: 'gold', name: 'finops_run_costs', layer: 'gold'});
CREATE (:Table {full_name: 'gold.pbf_estados_df', schema: 'gold', name: 'pbf_estados_df', layer: 'gold'});
CREATE (:Table {full_name: 'gold.pbf_municipios_df', schema: 'gold', name: 'pbf_municipios_df', layer: 'gold'});
CREATE (:Table {full_name: 'gold.rais_estados_ano', schema: 'gold', name: 'rais_estados_ano', layer: 'gold'});
CREATE (:Table {full_name: 'gold.uropro_estados_ano', schema: 'gold', name: 'uropro_estados_ano', layer: 'gold'});
CREATE (:Table {full_name: 'silver.emendas_uf_ano', schema: 'silver', name: 'emendas_uf_ano', layer: 'silver'});
CREATE (:Table {full_name: 'silver.equipamentos_uf_ano', schema: 'silver', name: 'equipamentos_uf_ano', layer: 'silver'});
CREATE (:Table {full_name: 'silver.finops_daily_spend', schema: 'silver', name: 'finops_daily_spend', layer: 'silver'});
CREATE (:Table {full_name: 'silver.finops_run_costs', schema: 'silver', name: 'finops_run_costs', layer: 'silver'});
CREATE (:Table {full_name: 'silver.ipca_deflators_2021', schema: 'silver', name: 'ipca_deflators_2021', layer: 'silver'});
CREATE (:Table {full_name: 'silver.pbf_total_municipio_mes', schema: 'silver', name: 'pbf_total_municipio_mes', layer: 'silver'});
CREATE (:Table {full_name: 'silver.pbf_total_uf_mes', schema: 'silver', name: 'pbf_total_uf_mes', layer: 'silver'});
CREATE (:Table {full_name: 'silver.populacao_municipio_ano', schema: 'silver', name: 'populacao_municipio_ano', layer: 'silver'});
CREATE (:Table {full_name: 'silver.populacao_uf_ano', schema: 'silver', name: 'populacao_uf_ano', layer: 'silver'});
CREATE (:Table {full_name: 'silver.rais_panel', schema: 'silver', name: 'rais_panel', layer: 'silver'});
CREATE (:Table {full_name: 'silver.rais_uf_ano', schema: 'silver', name: 'rais_uf_ano', layer: 'silver'});
CREATE (:Table {full_name: 'silver.sih_uropro_uf_ano', schema: 'silver', name: 'sih_uropro_uf_ano', layer: 'silver'});
CREATE (:Job {name: 'refresh populacao_uf_ano', domain: 'populacao'});
CREATE (:Job {name: 'refresh populacao_municipio_ano (5.570 munis × ano)', domain: 'populacao'});
CREATE (:Job {name: 'refresh PBF municipal (geobr + silver + gold + export)', domain: 'pbf'});
CREATE (:Job {name: 'refresh ipca_deflators_2021', domain: 'ipca'});
CREATE (:Job {name: 'refresh PBF (ingest → bronze → silver → gold → export)', domain: 'pbf'});
CREATE (:Job {name: 'refresh Equipamentos (ingest → bronze → silver → gold → export)', domain: 'equipamentos'});
CREATE (:Job {name: 'refresh RAIS (ingest → bronze → silver → gold → export)', domain: 'rais'});
CREATE (:Job {name: 'diagnostics RAIS (integrity check fonte → bronze)', domain: 'rais'});
CREATE (:Job {name: 'refresh Emendas (ingest → bronze → silver → gold → export)', domain: 'emendas'});
CREATE (:Job {name: 'refresh UroPro (ingest → bronze → silver → gold → export)', domain: 'uropro'});
CREATE (:Job {name: 'refresh FinOps (silver → gold → export)', domain: 'finops'});
CREATE (:Job {name: 'apply catalog/schema/table/column metadata + tags', domain: 'meta'});
CREATE (:Task {key: 'job_populacao_refresh::ingest_ibge', notebook_path: './notebooks/ingest/ibge_populacao.py'});
CREATE (:Task {key: 'job_populacao_refresh::bronze_ibge_populacao_raw', notebook_path: './notebooks/bronze/ibge_populacao_raw.py'});
CREATE (:Task {key: 'job_populacao_refresh::silver_populacao_uf_ano', notebook_path: './notebooks/silver/populacao_uf_ano.py'});
CREATE (:Task {key: 'job_populacao_municipios_refresh::ingest_ibge_pop_municipios', notebook_path: './notebooks/ingest/ibge_pop_municipios.py'});
CREATE (:Task {key: 'job_populacao_municipios_refresh::silver_populacao_municipio_ano', notebook_path: './notebooks/silver/populacao_municipio_ano.py'});
CREATE (:Task {key: 'job_pbf_municipios_pipeline::ingest_geobr_municipios', notebook_path: './notebooks/ingest/geobr_municipios.py'});
CREATE (:Task {key: 'job_pbf_municipios_pipeline::silver_pbf_total_municipio_mes', notebook_path: './notebooks/silver/pbf_total_municipio_mes.py'});
CREATE (:Task {key: 'job_pbf_municipios_pipeline::gold_pbf_municipios_df', notebook_path: './notebooks/gold/pbf_municipios_df.py'});
CREATE (:Task {key: 'job_pbf_municipios_pipeline::export_pbf_municipios_df_json', notebook_path: './notebooks/export/pbf_municipios_df_json.py'});
CREATE (:Task {key: 'job_ipca_refresh::ingest_bcb', notebook_path: './notebooks/ingest/bcb_ipca.py'});
CREATE (:Task {key: 'job_ipca_refresh::bronze_bcb_ipca_raw', notebook_path: './notebooks/bronze/bcb_ipca_raw.py'});
CREATE (:Task {key: 'job_ipca_refresh::silver_ipca_deflators_2021', notebook_path: './notebooks/silver/ipca_deflators_2021.py'});
CREATE (:Task {key: 'job_pbf_refresh::ingest_cgu_pbf_zips', notebook_path: './notebooks/ingest/cgu_pbf_zips.py'});
CREATE (:Task {key: 'job_pbf_refresh::bronze_pbf_pagamentos', notebook_path: './notebooks/bronze/pbf_pagamentos.py'});
CREATE (:Task {key: 'job_pbf_refresh::silver_pbf_total_uf_mes', notebook_path: './notebooks/silver/pbf_total_uf_mes.py'});
CREATE (:Task {key: 'job_pbf_refresh::gold_pbf_estados_df', notebook_path: './notebooks/gold/pbf_estados_df.py'});
CREATE (:Task {key: 'job_pbf_refresh::export_pbf_estados_df_json', notebook_path: './notebooks/export/pbf_estados_df_json.py'});
CREATE (:Task {key: 'job_pbf_refresh::export_platform_stats_json', notebook_path: './notebooks/export/platform_stats_json.py'});
CREATE (:Task {key: 'job_equipamentos_refresh::ingest_datasus_cnes_eq', notebook_path: './notebooks/ingest/datasus_cnes_eq.py'});
CREATE (:Task {key: 'job_equipamentos_refresh::bronze_cnes_equipamentos', notebook_path: './notebooks/bronze/cnes_equipamentos.py'});
CREATE (:Task {key: 'job_equipamentos_refresh::silver_equipamentos_uf_ano', notebook_path: './notebooks/silver/equipamentos_uf_ano.py'});
CREATE (:Task {key: 'job_equipamentos_refresh::gold_equipamentos_estados_ano', notebook_path: './notebooks/gold/equipamentos_estados_ano.py'});
CREATE (:Task {key: 'job_equipamentos_refresh::export_equipamentos_estados_ano_json', notebook_path: './notebooks/export/equipamentos_estados_ano_json.py'});
CREATE (:Task {key: 'job_rais_refresh::ingest_mte_rais', notebook_path: './notebooks/ingest/mte_rais.py'});
CREATE (:Task {key: 'job_rais_refresh::bronze_rais_vinculos', notebook_path: './notebooks/bronze/rais_vinculos.py'});
CREATE (:Task {key: 'job_rais_refresh::silver_rais_uf_ano', notebook_path: './notebooks/silver/rais_uf_ano.py'});
CREATE (:Task {key: 'job_rais_refresh::silver_rais_panel', notebook_path: './notebooks/silver/rais_panel.py'});
CREATE (:Task {key: 'job_rais_refresh::gold_rais_estados_ano', notebook_path: './notebooks/gold/rais_estados_ano.py'});
CREATE (:Task {key: 'job_rais_refresh::export_rais_estados_ano_json', notebook_path: './notebooks/export/rais_estados_ano_json.py'});
CREATE (:Task {key: 'job_rais_integrity::rais_integrity_check', notebook_path: './notebooks/diagnostics/rais_integrity.py'});
CREATE (:Task {key: 'job_emendas_refresh::ingest_cgu_emendas', notebook_path: './notebooks/ingest/cgu_emendas.py'});
CREATE (:Task {key: 'job_emendas_refresh::bronze_emendas_pagamentos', notebook_path: './notebooks/bronze/emendas_pagamentos.py'});
CREATE (:Task {key: 'job_emendas_refresh::silver_emendas_uf_ano', notebook_path: './notebooks/silver/emendas_uf_ano.py'});
CREATE (:Task {key: 'job_emendas_refresh::gold_emendas_estados_df', notebook_path: './notebooks/gold/emendas_estados_df.py'});
CREATE (:Task {key: 'job_emendas_refresh::export_emendas_estados_df_json', notebook_path: './notebooks/export/emendas_estados_df_json.py'});
CREATE (:Task {key: 'job_uropro_refresh::ingest_datasus_sih_rd', notebook_path: './notebooks/ingest/datasus_sih_rd.py'});
CREATE (:Task {key: 'job_uropro_refresh::bronze_sih_aih_rd_uropro', notebook_path: './notebooks/bronze/sih_aih_rd_uropro.py'});
CREATE (:Task {key: 'job_uropro_refresh::silver_sih_uropro_uf_ano', notebook_path: './notebooks/silver/sih_uropro_uf_ano.py'});
CREATE (:Task {key: 'job_uropro_refresh::gold_uropro_estados_ano', notebook_path: './notebooks/gold/uropro_estados_ano.py'});
CREATE (:Task {key: 'job_uropro_refresh::export_uropro_estados_ano_json', notebook_path: './notebooks/export/uropro_estados_ano_json.py'});
CREATE (:Task {key: 'job_finops_refresh::silver_finops_run_costs', notebook_path: './notebooks/silver/finops_run_costs.py'});
CREATE (:Task {key: 'job_finops_refresh::silver_finops_daily_spend', notebook_path: './notebooks/silver/finops_daily_spend.py'});
CREATE (:Task {key: 'job_finops_refresh::gold_finops_run_costs', notebook_path: './notebooks/gold/finops_run_costs.py'});
CREATE (:Task {key: 'job_finops_refresh::gold_finops_daily_spend', notebook_path: './notebooks/gold/finops_daily_spend.py'});
CREATE (:Task {key: 'job_finops_refresh::export_finops_summary_json', notebook_path: './notebooks/export/finops_summary_json.py'});
CREATE (:Task {key: 'job_apply_catalog_metadata::apply_metadata', notebook_path: './notebooks/_meta/apply_catalog_metadata.py'});

MATCH (j:Job {name: 'refresh populacao_uf_ano'}), (tk:Task {key: 'job_populacao_refresh::ingest_ibge'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (j:Job {name: 'refresh populacao_uf_ano'}), (tk:Task {key: 'job_populacao_refresh::bronze_ibge_populacao_raw'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_populacao_refresh::ingest_ibge'}), (b:Task {key: 'job_populacao_refresh::bronze_ibge_populacao_raw'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_populacao_refresh::bronze_ibge_populacao_raw'}), (tb:Table {full_name: 'bronze.ibge_populacao_raw'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_populacao_refresh::bronze_ibge_populacao_raw'}), (tb:Table {full_name: 'bronze.ibge_populacao_raw'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (j:Job {name: 'refresh populacao_uf_ano'}), (tk:Task {key: 'job_populacao_refresh::silver_populacao_uf_ano'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_populacao_refresh::bronze_ibge_populacao_raw'}), (b:Task {key: 'job_populacao_refresh::silver_populacao_uf_ano'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_populacao_refresh::silver_populacao_uf_ano'}), (tb:Table {full_name: 'bronze.ibge_populacao_raw'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_populacao_refresh::silver_populacao_uf_ano'}), (tb:Table {full_name: 'silver.populacao_uf_ano'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (j:Job {name: 'refresh populacao_municipio_ano (5.570 munis × ano)'}), (tk:Task {key: 'job_populacao_municipios_refresh::ingest_ibge_pop_municipios'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (tk:Task {key: 'job_populacao_municipios_refresh::ingest_ibge_pop_municipios'}), (tb:Table {full_name: 'bronze.ibge_municipios_populacao_raw'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_populacao_municipios_refresh::ingest_ibge_pop_municipios'}), (tb:Table {full_name: 'bronze.ibge_municipios_populacao_raw'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (j:Job {name: 'refresh populacao_municipio_ano (5.570 munis × ano)'}), (tk:Task {key: 'job_populacao_municipios_refresh::silver_populacao_municipio_ano'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_populacao_municipios_refresh::ingest_ibge_pop_municipios'}), (b:Task {key: 'job_populacao_municipios_refresh::silver_populacao_municipio_ano'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_populacao_municipios_refresh::silver_populacao_municipio_ano'}), (tb:Table {full_name: 'bronze.ibge_municipios_populacao_raw'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_populacao_municipios_refresh::silver_populacao_municipio_ano'}), (tb:Table {full_name: 'silver.populacao_municipio_ano'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (j:Job {name: 'refresh PBF municipal (geobr + silver + gold + export)'}), (tk:Task {key: 'job_pbf_municipios_pipeline::ingest_geobr_municipios'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (tk:Task {key: 'job_pbf_municipios_pipeline::ingest_geobr_municipios'}), (tb:Table {full_name: 'bronze.geobr_municipios_geo'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (tk:Task {key: 'job_pbf_municipios_pipeline::ingest_geobr_municipios'}), (tb:Table {full_name: 'bronze.geobr_municipios_meta'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (j:Job {name: 'refresh PBF municipal (geobr + silver + gold + export)'}), (tk:Task {key: 'job_pbf_municipios_pipeline::silver_pbf_total_municipio_mes'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_pbf_municipios_pipeline::ingest_geobr_municipios'}), (b:Task {key: 'job_pbf_municipios_pipeline::silver_pbf_total_municipio_mes'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_pbf_municipios_pipeline::silver_pbf_total_municipio_mes'}), (tb:Table {full_name: 'bronze.pbf_pagamentos'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_pbf_municipios_pipeline::silver_pbf_total_municipio_mes'}), (tb:Table {full_name: 'bronze.geobr_municipios_meta'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_pbf_municipios_pipeline::silver_pbf_total_municipio_mes'}), (tb:Table {full_name: 'silver.pbf_total_municipio_mes'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (j:Job {name: 'refresh PBF municipal (geobr + silver + gold + export)'}), (tk:Task {key: 'job_pbf_municipios_pipeline::gold_pbf_municipios_df'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_pbf_municipios_pipeline::silver_pbf_total_municipio_mes'}), (b:Task {key: 'job_pbf_municipios_pipeline::gold_pbf_municipios_df'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_pbf_municipios_pipeline::gold_pbf_municipios_df'}), (tb:Table {full_name: 'silver.populacao_municipio_ano'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_pbf_municipios_pipeline::gold_pbf_municipios_df'}), (tb:Table {full_name: 'silver.ipca_deflators_2021'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_pbf_municipios_pipeline::gold_pbf_municipios_df'}), (tb:Table {full_name: 'bronze.geobr_municipios_meta'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_pbf_municipios_pipeline::gold_pbf_municipios_df'}), (tb:Table {full_name: 'silver.pbf_total_municipio_mes'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_pbf_municipios_pipeline::gold_pbf_municipios_df'}), (tb:Table {full_name: 'gold.pbf_municipios_df'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (j:Job {name: 'refresh PBF municipal (geobr + silver + gold + export)'}), (tk:Task {key: 'job_pbf_municipios_pipeline::export_pbf_municipios_df_json'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_pbf_municipios_pipeline::gold_pbf_municipios_df'}), (b:Task {key: 'job_pbf_municipios_pipeline::export_pbf_municipios_df_json'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_pbf_municipios_pipeline::export_pbf_municipios_df_json'}), (tb:Table {full_name: 'gold.pbf_municipios_df'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (j:Job {name: 'refresh ipca_deflators_2021'}), (tk:Task {key: 'job_ipca_refresh::ingest_bcb'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (j:Job {name: 'refresh ipca_deflators_2021'}), (tk:Task {key: 'job_ipca_refresh::bronze_bcb_ipca_raw'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_ipca_refresh::ingest_bcb'}), (b:Task {key: 'job_ipca_refresh::bronze_bcb_ipca_raw'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_ipca_refresh::bronze_bcb_ipca_raw'}), (tb:Table {full_name: 'bronze.bcb_ipca_raw'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_ipca_refresh::bronze_bcb_ipca_raw'}), (tb:Table {full_name: 'bronze.bcb_ipca_raw'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (j:Job {name: 'refresh ipca_deflators_2021'}), (tk:Task {key: 'job_ipca_refresh::silver_ipca_deflators_2021'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_ipca_refresh::bronze_bcb_ipca_raw'}), (b:Task {key: 'job_ipca_refresh::silver_ipca_deflators_2021'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_ipca_refresh::silver_ipca_deflators_2021'}), (tb:Table {full_name: 'silver.ipca_deflators_2021'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_ipca_refresh::silver_ipca_deflators_2021'}), (tb:Table {full_name: 'bronze.bcb_ipca_raw'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_ipca_refresh::silver_ipca_deflators_2021'}), (tb:Table {full_name: 'silver.ipca_deflators_2021'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (j:Job {name: 'refresh PBF (ingest → bronze → silver → gold → export)'}), (tk:Task {key: 'job_pbf_refresh::ingest_cgu_pbf_zips'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (j:Job {name: 'refresh PBF (ingest → bronze → silver → gold → export)'}), (tk:Task {key: 'job_pbf_refresh::bronze_pbf_pagamentos'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_pbf_refresh::ingest_cgu_pbf_zips'}), (b:Task {key: 'job_pbf_refresh::bronze_pbf_pagamentos'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_pbf_refresh::bronze_pbf_pagamentos'}), (tb:Table {full_name: 'bronze.pbf_pagamentos'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_pbf_refresh::bronze_pbf_pagamentos'}), (tb:Table {full_name: 'bronze.pbf_pagamentos'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (j:Job {name: 'refresh PBF (ingest → bronze → silver → gold → export)'}), (tk:Task {key: 'job_pbf_refresh::silver_pbf_total_uf_mes'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_pbf_refresh::bronze_pbf_pagamentos'}), (b:Task {key: 'job_pbf_refresh::silver_pbf_total_uf_mes'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_pbf_refresh::silver_pbf_total_uf_mes'}), (tb:Table {full_name: 'bronze.pbf_pagamentos'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_pbf_refresh::silver_pbf_total_uf_mes'}), (tb:Table {full_name: 'silver.pbf_total_uf_mes'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (j:Job {name: 'refresh PBF (ingest → bronze → silver → gold → export)'}), (tk:Task {key: 'job_pbf_refresh::gold_pbf_estados_df'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_pbf_refresh::silver_pbf_total_uf_mes'}), (b:Task {key: 'job_pbf_refresh::gold_pbf_estados_df'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_pbf_refresh::gold_pbf_estados_df'}), (tb:Table {full_name: 'silver.populacao_uf_ano'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_pbf_refresh::gold_pbf_estados_df'}), (tb:Table {full_name: 'silver.pbf_total_uf_mes'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_pbf_refresh::gold_pbf_estados_df'}), (tb:Table {full_name: 'silver.ipca_deflators_2021'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_pbf_refresh::gold_pbf_estados_df'}), (tb:Table {full_name: 'gold.pbf_estados_df'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (j:Job {name: 'refresh PBF (ingest → bronze → silver → gold → export)'}), (tk:Task {key: 'job_pbf_refresh::export_pbf_estados_df_json'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_pbf_refresh::gold_pbf_estados_df'}), (b:Task {key: 'job_pbf_refresh::export_pbf_estados_df_json'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_pbf_refresh::export_pbf_estados_df_json'}), (tb:Table {full_name: 'gold.pbf_estados_df'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (j:Job {name: 'refresh PBF (ingest → bronze → silver → gold → export)'}), (tk:Task {key: 'job_pbf_refresh::export_platform_stats_json'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_pbf_refresh::export_pbf_estados_df_json'}), (b:Task {key: 'job_pbf_refresh::export_platform_stats_json'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (j:Job {name: 'refresh Equipamentos (ingest → bronze → silver → gold → export)'}), (tk:Task {key: 'job_equipamentos_refresh::ingest_datasus_cnes_eq'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (j:Job {name: 'refresh Equipamentos (ingest → bronze → silver → gold → export)'}), (tk:Task {key: 'job_equipamentos_refresh::bronze_cnes_equipamentos'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_equipamentos_refresh::ingest_datasus_cnes_eq'}), (b:Task {key: 'job_equipamentos_refresh::bronze_cnes_equipamentos'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_equipamentos_refresh::bronze_cnes_equipamentos'}), (tb:Table {full_name: 'bronze.cnes_equipamentos'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_equipamentos_refresh::bronze_cnes_equipamentos'}), (tb:Table {full_name: 'bronze.cnes_equipamentos'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (j:Job {name: 'refresh Equipamentos (ingest → bronze → silver → gold → export)'}), (tk:Task {key: 'job_equipamentos_refresh::silver_equipamentos_uf_ano'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_equipamentos_refresh::bronze_cnes_equipamentos'}), (b:Task {key: 'job_equipamentos_refresh::silver_equipamentos_uf_ano'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_equipamentos_refresh::silver_equipamentos_uf_ano'}), (tb:Table {full_name: 'silver.populacao_uf_ano'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_equipamentos_refresh::silver_equipamentos_uf_ano'}), (tb:Table {full_name: 'bronze.cnes_equipamentos'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_equipamentos_refresh::silver_equipamentos_uf_ano'}), (tb:Table {full_name: 'silver.equipamentos_uf_ano'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (j:Job {name: 'refresh Equipamentos (ingest → bronze → silver → gold → export)'}), (tk:Task {key: 'job_equipamentos_refresh::gold_equipamentos_estados_ano'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_equipamentos_refresh::silver_equipamentos_uf_ano'}), (b:Task {key: 'job_equipamentos_refresh::gold_equipamentos_estados_ano'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_equipamentos_refresh::gold_equipamentos_estados_ano'}), (tb:Table {full_name: 'silver.equipamentos_uf_ano'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_equipamentos_refresh::gold_equipamentos_estados_ano'}), (tb:Table {full_name: 'gold.equipamentos_estados_ano'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (j:Job {name: 'refresh Equipamentos (ingest → bronze → silver → gold → export)'}), (tk:Task {key: 'job_equipamentos_refresh::export_equipamentos_estados_ano_json'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_equipamentos_refresh::gold_equipamentos_estados_ano'}), (b:Task {key: 'job_equipamentos_refresh::export_equipamentos_estados_ano_json'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_equipamentos_refresh::export_equipamentos_estados_ano_json'}), (tb:Table {full_name: 'gold.equipamentos_estados_ano'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (j:Job {name: 'refresh RAIS (ingest → bronze → silver → gold → export)'}), (tk:Task {key: 'job_rais_refresh::ingest_mte_rais'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (j:Job {name: 'refresh RAIS (ingest → bronze → silver → gold → export)'}), (tk:Task {key: 'job_rais_refresh::bronze_rais_vinculos'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_rais_refresh::ingest_mte_rais'}), (b:Task {key: 'job_rais_refresh::bronze_rais_vinculos'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_rais_refresh::bronze_rais_vinculos'}), (tb:Table {full_name: 'bronze.rais_vinculos'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_rais_refresh::bronze_rais_vinculos'}), (tb:Table {full_name: 'bronze.rais_vinculos'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (j:Job {name: 'refresh RAIS (ingest → bronze → silver → gold → export)'}), (tk:Task {key: 'job_rais_refresh::silver_rais_uf_ano'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_rais_refresh::bronze_rais_vinculos'}), (b:Task {key: 'job_rais_refresh::silver_rais_uf_ano'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_rais_refresh::silver_rais_uf_ano'}), (tb:Table {full_name: 'bronze.rais_vinculos'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_rais_refresh::silver_rais_uf_ano'}), (tb:Table {full_name: 'silver.rais_uf_ano'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (j:Job {name: 'refresh RAIS (ingest → bronze → silver → gold → export)'}), (tk:Task {key: 'job_rais_refresh::silver_rais_panel'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_rais_refresh::bronze_rais_vinculos'}), (b:Task {key: 'job_rais_refresh::silver_rais_panel'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_rais_refresh::silver_rais_panel'}), (tb:Table {full_name: 'bronze.rais_vinculos'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_rais_refresh::silver_rais_panel'}), (tb:Table {full_name: 'silver.rais_panel'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (j:Job {name: 'refresh RAIS (ingest → bronze → silver → gold → export)'}), (tk:Task {key: 'job_rais_refresh::gold_rais_estados_ano'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_rais_refresh::silver_rais_uf_ano'}), (b:Task {key: 'job_rais_refresh::gold_rais_estados_ano'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_rais_refresh::gold_rais_estados_ano'}), (tb:Table {full_name: 'silver.populacao_uf_ano'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_rais_refresh::gold_rais_estados_ano'}), (tb:Table {full_name: 'silver.ipca_deflators_2021'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_rais_refresh::gold_rais_estados_ano'}), (tb:Table {full_name: 'silver.rais_uf_ano'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_rais_refresh::gold_rais_estados_ano'}), (tb:Table {full_name: 'gold.rais_estados_ano'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (j:Job {name: 'refresh RAIS (ingest → bronze → silver → gold → export)'}), (tk:Task {key: 'job_rais_refresh::export_rais_estados_ano_json'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_rais_refresh::gold_rais_estados_ano'}), (b:Task {key: 'job_rais_refresh::export_rais_estados_ano_json'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_rais_refresh::export_rais_estados_ano_json'}), (tb:Table {full_name: 'gold.rais_estados_ano'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (j:Job {name: 'diagnostics RAIS (integrity check fonte → bronze)'}), (tk:Task {key: 'job_rais_integrity::rais_integrity_check'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (tk:Task {key: 'job_rais_integrity::rais_integrity_check'}), (tb:Table {full_name: 'bronze.rais_vinculos'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (j:Job {name: 'refresh Emendas (ingest → bronze → silver → gold → export)'}), (tk:Task {key: 'job_emendas_refresh::ingest_cgu_emendas'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (j:Job {name: 'refresh Emendas (ingest → bronze → silver → gold → export)'}), (tk:Task {key: 'job_emendas_refresh::bronze_emendas_pagamentos'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_emendas_refresh::ingest_cgu_emendas'}), (b:Task {key: 'job_emendas_refresh::bronze_emendas_pagamentos'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_emendas_refresh::bronze_emendas_pagamentos'}), (tb:Table {full_name: 'bronze.emendas_pagamentos'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_emendas_refresh::bronze_emendas_pagamentos'}), (tb:Table {full_name: 'bronze.emendas_pagamentos'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (j:Job {name: 'refresh Emendas (ingest → bronze → silver → gold → export)'}), (tk:Task {key: 'job_emendas_refresh::silver_emendas_uf_ano'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_emendas_refresh::bronze_emendas_pagamentos'}), (b:Task {key: 'job_emendas_refresh::silver_emendas_uf_ano'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_emendas_refresh::silver_emendas_uf_ano'}), (tb:Table {full_name: 'bronze.emendas_pagamentos'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_emendas_refresh::silver_emendas_uf_ano'}), (tb:Table {full_name: 'silver.emendas_uf_ano'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (j:Job {name: 'refresh Emendas (ingest → bronze → silver → gold → export)'}), (tk:Task {key: 'job_emendas_refresh::gold_emendas_estados_df'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_emendas_refresh::silver_emendas_uf_ano'}), (b:Task {key: 'job_emendas_refresh::gold_emendas_estados_df'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_emendas_refresh::gold_emendas_estados_df'}), (tb:Table {full_name: 'silver.emendas_uf_ano'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_emendas_refresh::gold_emendas_estados_df'}), (tb:Table {full_name: 'silver.populacao_uf_ano'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_emendas_refresh::gold_emendas_estados_df'}), (tb:Table {full_name: 'silver.ipca_deflators_2021'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_emendas_refresh::gold_emendas_estados_df'}), (tb:Table {full_name: 'gold.emendas_estados_df'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (j:Job {name: 'refresh Emendas (ingest → bronze → silver → gold → export)'}), (tk:Task {key: 'job_emendas_refresh::export_emendas_estados_df_json'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_emendas_refresh::gold_emendas_estados_df'}), (b:Task {key: 'job_emendas_refresh::export_emendas_estados_df_json'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_emendas_refresh::export_emendas_estados_df_json'}), (tb:Table {full_name: 'gold.emendas_estados_df'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (j:Job {name: 'refresh UroPro (ingest → bronze → silver → gold → export)'}), (tk:Task {key: 'job_uropro_refresh::ingest_datasus_sih_rd'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (j:Job {name: 'refresh UroPro (ingest → bronze → silver → gold → export)'}), (tk:Task {key: 'job_uropro_refresh::bronze_sih_aih_rd_uropro'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_uropro_refresh::ingest_datasus_sih_rd'}), (b:Task {key: 'job_uropro_refresh::bronze_sih_aih_rd_uropro'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (j:Job {name: 'refresh UroPro (ingest → bronze → silver → gold → export)'}), (tk:Task {key: 'job_uropro_refresh::silver_sih_uropro_uf_ano'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_uropro_refresh::bronze_sih_aih_rd_uropro'}), (b:Task {key: 'job_uropro_refresh::silver_sih_uropro_uf_ano'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_uropro_refresh::silver_sih_uropro_uf_ano'}), (tb:Table {full_name: 'bronze.sih_aih_rd_uropro'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_uropro_refresh::silver_sih_uropro_uf_ano'}), (tb:Table {full_name: 'silver.sih_uropro_uf_ano'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (j:Job {name: 'refresh UroPro (ingest → bronze → silver → gold → export)'}), (tk:Task {key: 'job_uropro_refresh::gold_uropro_estados_ano'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_uropro_refresh::silver_sih_uropro_uf_ano'}), (b:Task {key: 'job_uropro_refresh::gold_uropro_estados_ano'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_uropro_refresh::gold_uropro_estados_ano'}), (tb:Table {full_name: 'silver.sih_uropro_uf_ano'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_uropro_refresh::gold_uropro_estados_ano'}), (tb:Table {full_name: 'silver.ipca_deflators_2021'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_uropro_refresh::gold_uropro_estados_ano'}), (tb:Table {full_name: 'silver.populacao_uf_ano'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_uropro_refresh::gold_uropro_estados_ano'}), (tb:Table {full_name: 'gold.uropro_estados_ano'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (j:Job {name: 'refresh UroPro (ingest → bronze → silver → gold → export)'}), (tk:Task {key: 'job_uropro_refresh::export_uropro_estados_ano_json'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_uropro_refresh::gold_uropro_estados_ano'}), (b:Task {key: 'job_uropro_refresh::export_uropro_estados_ano_json'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_uropro_refresh::export_uropro_estados_ano_json'}), (tb:Table {full_name: 'gold.uropro_estados_ano'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (j:Job {name: 'refresh FinOps (silver → gold → export)'}), (tk:Task {key: 'job_finops_refresh::silver_finops_run_costs'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (tk:Task {key: 'job_finops_refresh::silver_finops_run_costs'}), (tb:Table {full_name: 'silver.finops_run_costs'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (j:Job {name: 'refresh FinOps (silver → gold → export)'}), (tk:Task {key: 'job_finops_refresh::silver_finops_daily_spend'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (tk:Task {key: 'job_finops_refresh::silver_finops_daily_spend'}), (tb:Table {full_name: 'silver.finops_daily_spend'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (j:Job {name: 'refresh FinOps (silver → gold → export)'}), (tk:Task {key: 'job_finops_refresh::gold_finops_run_costs'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_finops_refresh::silver_finops_run_costs'}), (b:Task {key: 'job_finops_refresh::gold_finops_run_costs'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_finops_refresh::gold_finops_run_costs'}), (tb:Table {full_name: 'silver.finops_run_costs'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_finops_refresh::gold_finops_run_costs'}), (tb:Table {full_name: 'gold.finops_run_costs'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (j:Job {name: 'refresh FinOps (silver → gold → export)'}), (tk:Task {key: 'job_finops_refresh::gold_finops_daily_spend'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_finops_refresh::silver_finops_daily_spend'}), (b:Task {key: 'job_finops_refresh::gold_finops_daily_spend'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_finops_refresh::gold_finops_daily_spend'}), (tb:Table {full_name: 'silver.finops_daily_spend'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_finops_refresh::gold_finops_daily_spend'}), (tb:Table {full_name: 'gold.finops_daily_spend'}) CREATE (tk)-[:WRITES_TO]->(tb);
MATCH (j:Job {name: 'refresh FinOps (silver → gold → export)'}), (tk:Task {key: 'job_finops_refresh::export_finops_summary_json'}) CREATE (j)-[:HAS_TASK]->(tk);
MATCH (a:Task {key: 'job_finops_refresh::gold_finops_run_costs'}), (b:Task {key: 'job_finops_refresh::export_finops_summary_json'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (a:Task {key: 'job_finops_refresh::gold_finops_daily_spend'}), (b:Task {key: 'job_finops_refresh::export_finops_summary_json'}) CREATE (a)-[:PRECEDES]->(b);
MATCH (tk:Task {key: 'job_finops_refresh::export_finops_summary_json'}), (tb:Table {full_name: 'gold.finops_daily_spend'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (tk:Task {key: 'job_finops_refresh::export_finops_summary_json'}), (tb:Table {full_name: 'gold.finops_run_costs'}) CREATE (tk)-[:READS_FROM]->(tb);
MATCH (j:Job {name: 'apply catalog/schema/table/column metadata + tags'}), (tk:Task {key: 'job_apply_catalog_metadata::apply_metadata'}) CREATE (j)-[:HAS_TASK]->(tk);

MATCH (a:Table {full_name: 'bronze.ibge_populacao_raw'}), (b:Table {full_name: 'bronze.ibge_populacao_raw'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'bronze.ibge_populacao_raw'}), (b:Table {full_name: 'silver.populacao_uf_ano'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'bronze.ibge_municipios_populacao_raw'}), (b:Table {full_name: 'bronze.ibge_municipios_populacao_raw'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'bronze.ibge_municipios_populacao_raw'}), (b:Table {full_name: 'silver.populacao_municipio_ano'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'bronze.pbf_pagamentos'}), (b:Table {full_name: 'silver.pbf_total_municipio_mes'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'bronze.geobr_municipios_meta'}), (b:Table {full_name: 'silver.pbf_total_municipio_mes'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'silver.populacao_municipio_ano'}), (b:Table {full_name: 'gold.pbf_municipios_df'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'silver.ipca_deflators_2021'}), (b:Table {full_name: 'gold.pbf_municipios_df'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'bronze.geobr_municipios_meta'}), (b:Table {full_name: 'gold.pbf_municipios_df'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'silver.pbf_total_municipio_mes'}), (b:Table {full_name: 'gold.pbf_municipios_df'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'bronze.bcb_ipca_raw'}), (b:Table {full_name: 'bronze.bcb_ipca_raw'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'silver.ipca_deflators_2021'}), (b:Table {full_name: 'silver.ipca_deflators_2021'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'bronze.bcb_ipca_raw'}), (b:Table {full_name: 'silver.ipca_deflators_2021'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'bronze.pbf_pagamentos'}), (b:Table {full_name: 'bronze.pbf_pagamentos'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'bronze.pbf_pagamentos'}), (b:Table {full_name: 'silver.pbf_total_uf_mes'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'silver.populacao_uf_ano'}), (b:Table {full_name: 'gold.pbf_estados_df'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'silver.pbf_total_uf_mes'}), (b:Table {full_name: 'gold.pbf_estados_df'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'silver.ipca_deflators_2021'}), (b:Table {full_name: 'gold.pbf_estados_df'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'bronze.cnes_equipamentos'}), (b:Table {full_name: 'bronze.cnes_equipamentos'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'silver.populacao_uf_ano'}), (b:Table {full_name: 'silver.equipamentos_uf_ano'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'bronze.cnes_equipamentos'}), (b:Table {full_name: 'silver.equipamentos_uf_ano'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'silver.equipamentos_uf_ano'}), (b:Table {full_name: 'gold.equipamentos_estados_ano'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'bronze.rais_vinculos'}), (b:Table {full_name: 'bronze.rais_vinculos'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'bronze.rais_vinculos'}), (b:Table {full_name: 'silver.rais_uf_ano'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'bronze.rais_vinculos'}), (b:Table {full_name: 'silver.rais_panel'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'silver.populacao_uf_ano'}), (b:Table {full_name: 'gold.rais_estados_ano'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'silver.ipca_deflators_2021'}), (b:Table {full_name: 'gold.rais_estados_ano'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'silver.rais_uf_ano'}), (b:Table {full_name: 'gold.rais_estados_ano'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'bronze.emendas_pagamentos'}), (b:Table {full_name: 'bronze.emendas_pagamentos'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'bronze.emendas_pagamentos'}), (b:Table {full_name: 'silver.emendas_uf_ano'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'silver.emendas_uf_ano'}), (b:Table {full_name: 'gold.emendas_estados_df'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'silver.populacao_uf_ano'}), (b:Table {full_name: 'gold.emendas_estados_df'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'silver.ipca_deflators_2021'}), (b:Table {full_name: 'gold.emendas_estados_df'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'bronze.sih_aih_rd_uropro'}), (b:Table {full_name: 'silver.sih_uropro_uf_ano'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'silver.sih_uropro_uf_ano'}), (b:Table {full_name: 'gold.uropro_estados_ano'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'silver.ipca_deflators_2021'}), (b:Table {full_name: 'gold.uropro_estados_ano'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'silver.populacao_uf_ano'}), (b:Table {full_name: 'gold.uropro_estados_ano'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'silver.finops_run_costs'}), (b:Table {full_name: 'gold.finops_run_costs'}) CREATE (a)-[:FEEDS]->(b);
MATCH (a:Table {full_name: 'silver.finops_daily_spend'}), (b:Table {full_name: 'gold.finops_daily_spend'}) CREATE (a)-[:FEEDS]->(b);
